openapi: 3.0.0
info:
  title: "SynBioHub Submission Plugin API"
  version: "1.0.0"
  description: API specification for SynBioHub submission plugin endpoints
  
paths:
  /status:
    get:
      summary: Get plugin status
      description: Returns the status of the submission plugin
      responses:
        '200':
          description: Plugin is ready to handle requests
          content:
            text/plain:
              schema:
                type: string
                example: "Ready"
        '5XX':
          description: Plugin is not ready

  /evaluate:
    post:
      summary: Evaluate if plugin can handle the submission
      description: The evaluate endpoint checks if the plugin can handle the requested submission operation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                manifest:
                  type: object
                  properties:
                    files:
                      type: array
                      items:
                        type: object
                        properties:
                          filename:
                            type: string
                            description: The name of the file
                          type:
                            type: string
                            description: The Content-Type of the file
                          url:
                            type: string
                            format: uri
                            description: A URL where the file can be accessed
                        required:
                          - filename
                          - type
                          - url
                  required:
                    - files
              required:
                - manifest
      responses:
        '200':
          description: Plugin can handle the submission
        '4XX':
          description: Plugin cannot handle the submission or request is invalid
  
  /run:
    post:
      summary: Run the submission operation
      description: The run endpoint processes the submission and returns a file that represents the submission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                manifest:
                  type: object
                  properties:
                    files:
                      type: array
                      items:
                        type: object
                        properties:
                          filename:
                            type: string
                            description: The name of the file
                          type:
                            type: string
                            description: The Content-Type of the file
                          url:
                            type: string
                            format: uri
                            description: A URL where the file can be accessed
                        required:
                          - filename
                          - type
                          - url
                  required:
                    - files
                instanceUrl:
                  type: string
                  format: uri
                  description: The URL of the SynBioHub instance
              required:
                - manifest
                - instanceUrl
      responses:
        '200':
          description: Submission operation successful
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                description: The file representing the submission
        '4XX':
          description: Error processing submission
