openapi: 3.0.0
info:
  title: "SynBioHub Download Plugin API"
  version: "1.0.0"
  description: API specification for SynBioHub download plugin endpoints
  
paths:
  /evaluate:
    post:
      summary: Evaluate if plugin can handle the download request
      description: The evaluate endpoint checks if the plugin can handle the requested download operation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: The RDF type of the top-level object
              required:
                - type
      responses:
        '200':
          description: Plugin can handle the download request
        '4XX':
          description: Plugin cannot handle the download request or request is invalid
  
  /run:
    post:
      summary: Run the download operation
      description: The run endpoint processes the download request and returns the requested file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                complete_sbol:
                  type: string
                  format: uri
                  description: The single-use URL for the complete object to operate on
                shallow_sbol:
                  type: string
                  format: uri
                  description: The single-use URL for a summarized or truncated view of the object
                top_level:
                  type: string
                  format: uri
                  description: The top-level URL of the SBOL object
                instanceUrl:
                  type: string
                  format: uri
                  description: The top-level URL of the SBOL object
                size:
                  type: integer
                  description: A number representing an estimate of the size of the object, probably triple count
              required:
                - complete_sbol
                - top_level
      responses:
        '200':
          description: Download operation successful
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '4XX':
          description: Error processing download request

components:
  schemas:
    Plugin:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        version:
          type: string
